language: node_js
node_js:
  - '8'
install:
  - npm install
cache:
  directories:
    - '$HOME/.npm'
after_failure:
  - cat /home/travis/.npm/_logs/*.log
deploy:
  provider: npm
  email: stw@linux.com
  api_key: $NPM_TOKEN
  on:
    branch: master
